### ISSUE TITLE
Why quantized by starcoder.cpp and by ggml example models are different?

### ISSUE THREAD

**Issue by s-kostyaev** [bigcode-project/starcoder.cpp#11]
Looks like quantization, inference and model format are different between starcoder.cpp and upstream ggml. Why? And Why models are incompatible? For example if I try to use inference in starcoder.cpp model quantized by ggml example code I will see segmentation fault. Maybe need to update code to be compatible with upsteam?

**Comment by s-kostyaev** [comment]
If I quantize model by `starcoder.cpp` and then run with `starcoder.cpp` all works fine. But if I quantize model by latest `ggml` and then try to run it with `starcoder.cpp` I will see segfault.

**Comment by s-kostyaev** [comment]
Models quantized by latest version of `ggml` can be found here: https://huggingface.co/NeoDim

**Comment by NouamaneTazi** [comment]
> Also hash sums are different between models quantized by ggml and by starcoder.cpp

hash sum indicates the ggml version used to build your checkpoint. It's normal that if your checkpoint's hash is different from the library it won't run properly

I suggest you use the same library to convert and run the model you want
