### ISSUE TITLE
trying to ggml the starpii but seeing following error, anything i need to further check?

### ISSUE THREAD

**Issue by wesleysanjose** [bigcode-project/starcoder.cpp#12]
Loading model:  /Users/abc/dev/starpii
If you want to use `BertLMHeadModel` as a standalone, add `is_decoder=True.`
Some weights of the model checkpoint at /Users/abc/dev/starpii were not used when initializing BertLMHeadModel: ['classifier.bias', 'classifier.weight']
- This IS expected if you are initializing BertLMHeadModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertLMHeadModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Model loaded:  /Users/abc/dev/starpii
{'return_dict': True, 'output_hidden_states': False, 'output_attentions': False, 'torchscript': False, 'torch_dtype': 'float32', 'use_bfloat16': False, 'tf_legacy_loss': False, 'pruned_heads': {}, 'tie_word_embeddings': True, 'is_encoder_decoder': False, 'is_decoder': False, 'cross_attention_hidden_size': None, 'add_cross_attention': False, 'tie_encoder_decoder': False, 'max_length': 20, 'min_length': 0, 'do_sample': False, 'early_stopping': False, 'num_beams': 1, 'num_beam_groups': 1, 'diversity_penalty': 0.0, 'temperature': 1.0, 'top_k': 50, 'top_p': 1.0, 'typical_p': 1.0, 'repetition_penalty': 1.0, 'length_penalty': 1.0, 'no_repeat_ngram_size': 0, 'encoder_no_repeat_ngram_size': 0, 'bad_words_ids': None, 'num_return_sequences': 1, 'chunk_size_feed_forward': 0, 'output_scores': False, 'return_dict_in_generate': False, 'forced_bos_token_id': None, 'forced_eos_token_id': None, 'remove_invalid_values': False, 'exponential_decay_length_penalty': None, 'suppress_tokens': None, 'begin_suppress_tokens': None, 'architectures': ['BertForTokenClassification'], 'finetuning_task': None, 'id2label': {0: 'O', 1: 'B-AMBIGUOUS', 2: 'I-AMBIGUOUS', 3: 'B-EMAIL', 4: 'I-EMAIL', 5: 'B-IP_ADDRESS', 6: 'I-IP_ADDRESS', 7: 'B-KEY', 8: 'I-KEY', 9: 'B-NAME', 10: 'I-NAME', 11: 'B-PASSWORD', 12: 'I-PASSWORD', 13: 'B-USERNAME', 14: 'I-USERNAME'}, 'label2id': {'B-AMBIGUOUS': 1, 'B-EMAIL': 3, 'B-IP_ADDRESS': 5, 'B-KEY': 7, 'B-NAME': 9, 'B-PASSWORD': 11, 'B-USERNAME': 13, 'I-AMBIGUOUS': 2, 'I-EMAIL': 4, 'I-IP_ADDRESS': 6, 'I-KEY': 8, 'I-NAME': 10, 'I-PASSWORD': 12, 'I-USERNAME': 14, 'O': 0}, 'tokenizer_class': None, 'prefix': None, 'bos_token_id': None, 'pad_token_id': 49152, 'eos_token_id': None, 'sep_token_id': None, 'decoder_start_token_id': None, 'task_specific_params': None, 'problem_type': None, '_name_or_path': '/Users/abc/dev/starpii', 'transformers_version': '4.28.1', 'model_type': 'bert', 'vocab_size': 49153, 'hidden_size': 768, 'num_hidden_layers': 12, 'num_attention_heads': 12, 'hidden_act': 'gelu', 'intermediate_size': 3072, 'hidden_dropout_prob': 0.1, 'attention_probs_dropout_prob': 0.1, 'max_position_embeddings': 1024, 'type_vocab_size': 2, 'initializer_range': 0.02, 'layer_norm_eps': 1e-12, 'position_embedding_type': 'absolute', 'use_cache': True, 'classifier_dropout': None}
Saving ggml model to:  models//Users/abc/dev/starpii-ggml.bin
Traceback (most recent call last):
  File "/Users/abc/dev/starcoder.cpp/convert-hf-to-ggml.py", line 78, in <module>
    fout.write(struct.pack("i", hparams["n_positions"])) # n_ctx
KeyError: 'n_positions'

**Comment by NouamaneTazi** [comment]
Unfortunately only the following are supported for now:

- bigcode/starcoder
- bigcode/gpt_bigcode-santacoder
