### ISSUE TITLE
context memory pool

### ISSUE THREAD

**Issue by Leterax** [bigcode-project/starcoder.cpp#3]
When running the StarCoder model quantized using "q5_1" with a medium-sized context (3500 tokens) I run into this error:
```
ggml_new_tensor_impl: not enough space in the context's memory pool (needed 412241472, available 411791504)
Segmentation fault (core dumped)
```
How can I increase the context memory pool size?

**Comment by NouamaneTazi** [comment]
Yes, I'm able to reproduce this issue! We're investigating a fix here: https://github.com/ggerganov/ggml/pull/175
