### ISSUE TITLE
Starcoder conversion and quantization instructions

### ISSUE THREAD

**Issue by aseok** [bigcode-project/starcoder.cpp#5]
Hi.
Pls provide conversion and quantization instructions of the main starcoder model files.

**Comment by NouamaneTazi** [comment]
You can find the instructions here: https://github.com/bigcode-project/starcoder.cpp#quick-start

**Comment by asingleoat** [comment]
>how to pass the model files in quantization command?

for the sharded model conversion don't pass the filenames, pass the directory:
`$ python convert-hf-to-ggml.py ../starcoder`

then quantization is as in the README example:
`$ ./quantize starcoder-ggml.bin starcoder-ggml-q4_1.bin 3`

**Comment by NouamaneTazi** [comment]
Does that fix your issue @aseok?
